# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillpm < Formula
  desc "Local-first skill package manager for AI agents"
  homepage "https://github.com/eddieran/skillpm"
  version "3.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Darwin_x86_64.tar.gz"
      sha256 "d86f7ed6e50696c89ffaa62b15d2629f86d7b1d9ea759248628db7342b9acbcd"

      define_method(:install) do
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Darwin_arm64.tar.gz"
      sha256 "0f7fe1cdeff1bfe60a205a90dde94145f97a35290ad13451e06a033eeaf1e7d2"

      define_method(:install) do
        bin.install "skillpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Linux_x86_64.tar.gz"
      sha256 "7f9e36a3a5e8840e778d2efe06aad40b08ebe42a9c1e4da4d397203938f763bb"
      define_method(:install) do
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Linux_arm64.tar.gz"
      sha256 "210594908e0471dba2ca651b8cf72f175d1293ce09b5f921f0f4fd34d039125b"
      define_method(:install) do
        bin.install "skillpm"
      end
    end
  end

  test do
    system "#{bin}/skillpm version"
  end
end
