# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillpm < Formula
  desc "Local-first skill package manager for AI agents"
  homepage "https://github.com/eddieran/skillpm"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eddieran/skillpm/releases/download/v0.1.1/skillpm_Darwin_x86_64.tar.gz"
      sha256 "6aed153dd8f252a67272bc7202295abd9b699dbfee488ac211570f741068c283"

      def install
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eddieran/skillpm/releases/download/v0.1.1/skillpm_Darwin_arm64.tar.gz"
      sha256 "83408b00a7137ff7aa8652c1f0da11ff5e8591d709f62dac70070e678a416716"

      def install
        bin.install "skillpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v0.1.1/skillpm_Linux_x86_64.tar.gz"
      sha256 "27670541c778a3588623e8a3b3d3f560b0dc3ce1a24cbe96f632d779bdec0b24"
      def install
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v0.1.1/skillpm_Linux_arm64.tar.gz"
      sha256 "d3a9d6a9f820ee19f2a2370f4bcd741185dbed4a55e4af7705d95577a0004af7"
      def install
        bin.install "skillpm"
      end
    end
  end

  test do
    system "#{bin}/skillpm version"
  end
end
