# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillpm < Formula
  desc "Local-first skill package manager for AI agents"
  homepage "https://github.com/eddieran/skillpm"
  version "3.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Darwin_x86_64.tar.gz"
      sha256 "61be0ba3c5a9a8524357d9b6f1b8a4a1e79f64903dfb5a300f4c6a1e3f25c7f5"

      define_method(:install) do
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Darwin_arm64.tar.gz"
      sha256 "7697b5d92bc69fb73f589db737f1ab293785e9ef86bcf111437b34fac2da3984"

      define_method(:install) do
        bin.install "skillpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Linux_x86_64.tar.gz"
      sha256 "9293c8eb9bde1b1c2407b9d8eb22c339b22720bec85999dc93c3ea2ac07a7682"
      define_method(:install) do
        bin.install "skillpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eddieran/skillpm/releases/download/v3.0.0/skillpm_Linux_arm64.tar.gz"
      sha256 "fd06c087a55ace90823f6025624ca127c6f20eb728d718e0c4a0a4e8086516ad"
      define_method(:install) do
        bin.install "skillpm"
      end
    end
  end

  test do
    system "#{bin}/skillpm version"
  end
end
